#!/usr/bin/env bash

branch=$1

test -z $branch && echo "Usage: git review <branch name>" 1>&2 && exit 1

git fetch origin $branch
git checkout $branch
git reset --hard origin/$branch
git pull origin main --rebase

git status
